os: linux
dist: bionic
language: python

python:
  - "2.7.16"

services:
  - docker

install: true

branches:
  - develop
  - master

jobs:
  include:
    - name: "Test image build"
      script: ./scripts/build.sh
      after_failure: docker-compose logs
      if: tag IS blank
